/* Textos compartidos por celula.html (3D) y celula2d.html (2D):
   cada estructura con su nombre, color, descripción, funciones y dato curioso. */
(function () {
  var INFO = {
    euk: {
      kicker: 'Célula animal', title: 'Célula eucariota', color: '#5ec8ff', umPerUnit: 2.0,
      badge: ['Célula eucariota animal', 'Modelo esquemático · proporciones aproximadas'],
      desc: 'Tiene un núcleo verdadero rodeado por una envoltura y un sistema de orgánulos membranosos que se reparten el trabajo, como una fábrica con departamentos. Animales, plantas, hongos y protistas están formados por este tipo de célula.',
      facts: [['Tamaño', '10–100 µm'], ['Núcleo', 'Sí, con envoltura'], ['ADN', 'Lineal, con histonas'], ['Ribosomas', '80S'], ['Orgánulos', 'Con membrana'], ['División', 'Mitosis / meiosis']],
      parts: [
        { id: 'membrana', name: 'Membrana plasmática', color: '#5ec8ff', cat: 'Membrana', size: '7–10 nm de grosor',
          desc: 'Bicapa de fosfolípidos con proteínas, colesterol y glúcidos (glucocáliz) que envuelve a la célula. Según el modelo de mosaico fluido, sus componentes se desplazan lateralmente.',
          fn: ['Permeabilidad selectiva: controla qué entra y qué sale.', 'Transporte pasivo y activo mediante canales, transportadores y bombas.', 'Reconoce señales químicas gracias a sus receptores.', 'Endocitosis y exocitosis de moléculas grandes.'],
          fact: 'Es tan delgada que harían falta unas 10.000 membranas apiladas para igualar el grosor de una hoja de papel.' },
        { id: 'citoplasma', name: 'Citoplasma', color: '#7fd4ff', cat: 'Medio interno', size: '≈ 50 % del volumen celular',
          desc: 'Espacio entre la membrana y el núcleo. Está formado por el citosol —un gel acuoso rico en proteínas, iones y metabolitos— y los orgánulos suspendidos en él. Las partículas en movimiento representan las corrientes citoplasmáticas.',
          fn: ['Sede de la glucólisis y de muchas reacciones metabólicas.', 'Medio de transporte de sustancias.', 'Almacena reservas como glucógeno y gotas de lípidos.'],
          fact: 'El citosol tiene entre 70 y 80 % de agua, pero está tan lleno de proteínas que se comporta más como un gel que como un líquido.' },
        { id: 'nucleo', name: 'Núcleo', color: '#a46cf0', cat: 'Orgánulo · doble membrana', size: '5–10 µm de diámetro',
          desc: 'El centro de control de la célula. Guarda el ADN y regula qué genes se expresan, cuándo y en qué cantidad.',
          fn: ['Almacena y protege la información genética.', 'Transcripción: copia los genes a ARN mensajero.', 'Replica el ADN antes de la división celular.'],
          fact: 'Si se estirara el ADN de un solo núcleo humano mediría unos 2 metros de largo.' },
        { id: 'envoltura', name: 'Envoltura nuclear y poros', short: 'Envoltura nuclear', color: '#d2a8ff', cat: 'Doble membrana', size: 'Poros de ≈ 120 nm',
          desc: 'Doble membrana que rodea al núcleo y se continúa con el retículo endoplasmático. Está atravesada por miles de complejos de poro nuclear.',
          fn: ['Separa el material genético del citoplasma.', 'Los poros regulan la salida de ARN y la entrada de proteínas.', 'Sostiene la cromatina mediante la lámina nuclear.'],
          fact: 'Un núcleo típico tiene entre 3.000 y 5.000 poros, y por cada uno pueden pasar cientos de moléculas por segundo.' },
        { id: 'nucleolo', name: 'Nucléolo', color: '#6a5dff', cat: 'Región sin membrana', size: '1–2 µm',
          desc: 'Región densa del núcleo, sin membrana, donde se transcriben los genes del ARN ribosómico.',
          fn: ['Sintetiza el ARN ribosómico (ARNr).', 'Ensambla las subunidades de los ribosomas.', 'Participa en la respuesta celular al estrés.'],
          fact: 'Las células que fabrican muchas proteínas, como las del páncreas, tienen nucléolos grandes y a veces varios.' },
        { id: 'cromatina', name: 'Cromatina', color: '#9a5ae6', cat: 'ADN + proteínas', size: 'Fibra de 10–30 nm',
          desc: 'Complejo de ADN e histonas que llena el núcleo. Puede estar laxa (eucromatina, activa) o compacta (heterocromatina, junto a la envoltura) y se condensa en cromosomas durante la división.',
          fn: ['Empaqueta el ADN dentro del núcleo.', 'Regula el acceso a los genes (epigenética).', 'Forma los cromosomas en la mitosis.'],
          fact: 'El ADN se enrolla en "carretes" de histonas llamados nucleosomas, como cuentas de un collar.' },
        { id: 'rer', name: 'Retículo endoplasmático rugoso', short: 'RE rugoso', color: '#f07ca0', cat: 'Orgánulo · membrana simple', size: 'Hasta 50 % de las membranas',
          desc: 'Red de sacos aplanados (cisternas) cubiertos de ribosomas y unida a la envoltura nuclear. Esos ribosomas le dan su aspecto "rugoso".',
          fn: ['Síntesis de proteínas de secreción y de membrana.', 'Plegamiento y control de calidad de proteínas.', 'Inicio de la glicosilación.'],
          fact: 'Es muy abundante en células secretoras, como las que producen anticuerpos o enzimas digestivas.' },
        { id: 'rel', name: 'Retículo endoplasmático liso', short: 'RE liso', color: '#c6e05f', cat: 'Orgánulo · membrana simple', size: 'Túbulos de 30–60 nm',
          desc: 'Red de túbulos interconectados sin ribosomas, en continuidad con el RE rugoso.',
          fn: ['Síntesis de lípidos, fosfolípidos y hormonas esteroideas.', 'Detoxificación de fármacos y venenos (sobre todo en el hígado).', 'Almacena y libera calcio (Ca²⁺).'],
          fact: 'En las células musculares se llama retículo sarcoplásmico, y el calcio que libera dispara cada contracción.' },
        { id: 'golgi', name: 'Aparato de Golgi', color: '#ff9b45', cat: 'Orgánulo · membrana simple', size: '1–3 µm',
          desc: 'Pila de cisternas aplanadas con una cara cis, que recibe material del RE, y una cara trans, que despacha vesículas. Funciona como el "correo" de la célula.',
          fn: ['Modifica proteínas y lípidos (glicosilación).', 'Clasifica y empaqueta moléculas en vesículas.', 'Forma lisosomas y vesículas de secreción.'],
          fact: 'Lo describió Camillo Golgi en 1898 con una tinción de plata; durante décadas se dudó de que existiera.' },
        { id: 'mitocondrias', name: 'Mitocondrias', color: '#e5484d', cat: 'Orgánulo · doble membrana', size: '0,5–1 × 1–4 µm',
          desc: 'Orgánulos con doble membrana: la interna se pliega en crestas que aumentan su superficie. Tienen ADN y ribosomas propios.',
          fn: ['Respiración celular: producen la mayor parte del ATP.', 'Ciclo de Krebs en la matriz y cadena respiratoria en las crestas.', 'Regulan el calcio y la muerte celular programada (apoptosis).'],
          fact: 'Descienden de bacterias que fueron "adoptadas" por otra célula hace más de 1.500 millones de años (teoría endosimbiótica).' },
        { id: 'ribosomas', name: 'Ribosomas (80S)', short: 'Ribosomas', color: '#5b60ff', cat: 'Sin membrana', size: '25–30 nm',
          desc: 'Complejos de ARN ribosómico y proteínas formados por dos subunidades (60S + 40S). Pueden estar libres en el citosol, agrupados en polisomas, o unidos al RE rugoso.',
          fn: ['Traducen el ARN mensajero en proteínas.', 'Los libres fabrican proteínas para el citosol.', 'Los unidos al RER fabrican proteínas de secreción y de membrana.'],
          fact: 'Una sola célula puede tener varios millones de ribosomas trabajando a la vez.' },
        { id: 'lisosomas', name: 'Lisosomas', color: '#ffd166', cat: 'Orgánulo · membrana simple', size: '0,1–1,2 µm',
          desc: 'Vesículas con más de 50 enzimas digestivas (hidrolasas) que trabajan en un interior ácido, con pH de 4,5 a 5.',
          fn: ['Digestión intracelular de macromoléculas.', 'Autofagia: reciclan orgánulos viejos o dañados.', 'Degradan bacterias y partículas fagocitadas.'],
          fact: 'Su pH ácido es una medida de seguridad: si sus enzimas escapan al citosol (pH 7,2) casi no funcionan.' },
        { id: 'peroxisomas', name: 'Peroxisomas', color: '#5cd18a', cat: 'Orgánulo · membrana simple', size: '0,1–1 µm',
          desc: 'Vesículas con enzimas oxidativas como la catalasa; muchas muestran un núcleo cristalino de urato oxidasa.',
          fn: ['Degradan ácidos grasos de cadena muy larga.', 'Descomponen el peróxido de hidrógeno (H₂O₂) en agua y oxígeno.', 'Participan en la síntesis de lípidos de la mielina.'],
          fact: 'La catalasa es una de las enzimas más rápidas que existen: procesa millones de moléculas de H₂O₂ por segundo.' },
        { id: 'vesiculas', name: 'Vesículas de transporte', short: 'Vesículas', color: '#bfe4ff', cat: 'Membrana simple', size: '50–200 nm',
          desc: 'Pequeñas esferas de membrana que llevan carga entre el RE, el Golgi, la membrana y los lisosomas. En el modelo se las ve viajar por la célula.',
          fn: ['Transporte del RE al Golgi.', 'Secreción hacia el exterior por exocitosis.', 'Captación de material por endocitosis.'],
          fact: 'Las proteínas motoras cinesina y dineína "caminan" sobre los microtúbulos con pasos de 8 nm.' },
        { id: 'centrosoma', name: 'Centrosoma y centriolos', short: 'Centrosoma', color: '#ff4fa3', cat: 'Sin membrana', size: 'Centriolos de 0,2 × 0,5 µm',
          desc: 'Par de centriolos perpendiculares, cada uno con 9 tripletes de microtúbulos, rodeados de material pericentriolar.',
          fn: ['Principal centro organizador de microtúbulos.', 'Forma el huso mitótico durante la división.', 'Origina los cuerpos basales de cilios y flagelos.'],
          fact: 'Es típico de las células animales: la mayoría de las células vegetales no tiene centriolos.' },
        { id: 'citoesqueleto', name: 'Citoesqueleto', color: '#8fd8ff', cat: 'Red de proteínas', size: '7–25 nm de grosor',
          desc: 'Red dinámica de microtúbulos (25 nm), filamentos intermedios (10 nm) y microfilamentos de actina (7 nm). Los destellos que recorren los microtúbulos representan el transporte de carga.',
          fn: ['Da forma y resistencia mecánica a la célula.', 'Sirve de vía para el transporte de vesículas y orgánulos.', 'Permite el movimiento celular y la división.'],
          fact: 'Los microtúbulos crecen y se desarman continuamente: es lo que se llama inestabilidad dinámica.' },
        { id: 'cilios', name: 'Cilios', color: '#d6ecff', cat: 'Prolongación de membrana', size: '0,25 µm × 5–10 µm',
          desc: 'Prolongaciones móviles sostenidas por un axonema de microtúbulos en disposición 9 + 2. Baten coordinados en ondas metacrónicas.',
          fn: ['Desplazan líquidos y partículas, como el moco en las vías respiratorias.', 'Permiten nadar a algunos protistas.', 'El cilio primario funciona como antena sensorial.'],
          fact: 'Cada célula de la tráquea tiene unos 200 cilios que baten entre 10 y 20 veces por segundo.' },
      ],
    },
    pro: {
      kicker: 'Bacteria bacilar', title: 'Célula procariota', color: '#4fd38b', umPerUnit: 0.26,
      badge: ['Célula procariota · bacilo', 'Modelo esquemático · proporciones aproximadas'],
      desc: 'No tiene núcleo ni orgánulos membranosos: su ADN está libre en el citoplasma, en el nucleoide. Son las células más antiguas (unos 3.500 millones de años) y las más abundantes del planeta: bacterias y arqueas.',
      facts: [['Tamaño', '0,5–5 µm'], ['Núcleo', 'No (nucleoide)'], ['ADN', 'Circular + plásmidos'], ['Ribosomas', '70S'], ['Orgánulos', 'Sin membrana'], ['División', 'Fisión binaria']],
      parts: [
        { id: 'capsula', name: 'Cápsula', color: '#2bb673', cat: 'Envoltura externa', size: '0,2–1 µm',
          desc: 'Capa gelatinosa de polisacáridos (a veces de proteínas) que rodea a muchas bacterias por fuera de la pared.',
          fn: ['Protege de la desecación y de la fagocitosis.', 'Facilita la adhesión y la formación de biopelículas.', 'Es un factor de virulencia en patógenos como el neumococo.'],
          fact: 'En 1928 Griffith descubrió la "transformación" bacteriana comparando neumococos con y sin cápsula.' },
        { id: 'pared', name: 'Pared celular', color: '#e05a4b', cat: 'Envoltura', size: '10–80 nm',
          desc: 'Malla rígida de peptidoglucano (mureína) por fuera de la membrana. Es gruesa en las bacterias Gram positivas y delgada, con una membrana externa, en las Gram negativas.',
          fn: ['Da forma a la célula (bacilo, coco, espirilo).', 'Resiste la presión osmótica y evita que la célula estalle.', 'Es el blanco de antibióticos como la penicilina.'],
          fact: 'La tinción de Gram, inventada en 1884, clasifica a las bacterias justamente según esta pared.' },
        { id: 'membrana', name: 'Membrana plasmática', color: '#f4d03f', cat: 'Membrana', size: '7–8 nm',
          desc: 'Bicapa lipídica con proteínas, similar a la eucariota. Como no hay mitocondrias, en ella ocurren la respiración y la síntesis de ATP.',
          fn: ['Transporte selectivo de nutrientes e iones.', 'Cadena respiratoria y ATP sintasa.', 'Anclaje del motor flagelar y síntesis de la pared.'],
          fact: 'El flujo de protones a través de esta membrana es lo que hace girar el motor del flagelo.' },
        { id: 'citoplasma', name: 'Citoplasma', color: '#5fa8e8', cat: 'Medio interno', size: '≈ 80 % agua',
          desc: 'Citosol sin compartimentos membranosos internos, muy concentrado en proteínas, ribosomas y metabolitos.',
          fn: ['Sede del metabolismo (glucólisis, biosíntesis).', 'Contiene el nucleoide, los ribosomas y las inclusiones.', 'Allí la transcripción y la traducción ocurren a la vez.'],
          fact: 'En las bacterias un gen puede empezar a traducirse mientras todavía se está transcribiendo.' },
        { id: 'nucleoide', name: 'Nucleoide (cromosoma)', short: 'Nucleoide', color: '#e63946', cat: 'Región sin membrana', size: 'ADN de ≈ 1,5 mm',
          desc: 'Región irregular donde está el cromosoma bacteriano: una única molécula de ADN circular, superenrollada y sin histonas verdaderas.',
          fn: ['Contiene los genes esenciales de la célula.', 'Se replica y se reparte durante la fisión binaria.', 'Lo organizan proteínas asociadas como HU y H-NS.'],
          fact: 'El cromosoma de E. coli tiene 4,6 millones de pares de bases y mide 1,5 mm: ¡unas 700 veces el largo de la bacteria!' },
        { id: 'plasmidos', name: 'Plásmidos', color: '#7bed9f', cat: 'ADN extracromosómico', size: '1–200 kb',
          desc: 'Pequeñas moléculas de ADN circular, independientes del cromosoma, que se replican por su cuenta.',
          fn: ['Portan genes accesorios (resistencia a antibióticos, toxinas).', 'Se transfieren entre bacterias por conjugación.', 'Se usan como vectores en ingeniería genética.'],
          fact: 'Gracias a los plásmidos la resistencia a antibióticos puede pasar de una especie bacteriana a otra.' },
        { id: 'ribosomas', name: 'Ribosomas (70S)', short: 'Ribosomas', color: '#7a80d8', cat: 'Sin membrana', size: '≈ 20 nm',
          desc: 'Más pequeños que los eucariotas y formados por subunidades 50S y 30S. Están dispersos por todo el citoplasma.',
          fn: ['Traducen el ARNm en proteínas.', 'Pueden traducir mientras el ARNm se sintetiza.', 'Son blanco de antibióticos como tetraciclinas y estreptomicina.'],
          fact: 'Una bacteria de crecimiento rápido puede tener hasta 70.000 ribosomas.' },
        { id: 'inclusiones', name: 'Inclusiones', color: '#f4a261', cat: 'Gránulos de reserva', size: '0,1–1 µm',
          desc: 'Depósitos de sustancias de reserva en el citoplasma, como glucógeno, polifosfato (volutina) o polihidroxibutirato (PHB).',
          fn: ['Almacenan carbono, energía o fosfato.', 'Permiten sobrevivir en épocas de escasez.', 'Algunas, como los magnetosomas, orientan a la bacteria.'],
          fact: 'El PHB que acumulan algunas bacterias se usa para fabricar plásticos biodegradables.' },
        { id: 'pili', name: 'Pili y fimbrias', short: 'Pili', color: '#5fd39a', cat: 'Apéndices proteicos', size: '2–10 nm × hasta 2 µm',
          desc: 'Filamentos de pilina más finos y cortos que el flagelo. Las fimbrias son numerosas; el pilus sexual, largo y único, se ve sobresaliendo del resto.',
          fn: ['Adhesión a superficies y a células del huésped.', 'Conjugación: el pilus sexual une dos bacterias para transferir ADN.', 'Algunos permiten moverse a "tirones" (twitching).'],
          fact: 'Los pili tipo IV se retraen con una fuerza enorme para su tamaño: más de 100 piconewtons.' },
        { id: 'flagelo', name: 'Flagelo', color: '#27a065', cat: 'Apéndice de locomoción', size: '20 nm × 5–20 µm',
          desc: 'Filamento helicoidal de flagelina unido por un gancho a un motor rotatorio incrustado en la membrana y la pared.',
          fn: ['Propulsa a la bacteria girando como una hélice.', 'Permite la quimiotaxis: nadar hacia nutrientes o lejos de tóxicos.', 'El motor puede invertir el giro para cambiar de dirección.'],
          fact: 'El motor flagelar puede girar a más de 100.000 rpm y cambiar de sentido en milisegundos.' },
      ],
    },
  };
  var CMP = {
    rows: [
      ['Tamaño típico', '10–100 µm', '0,5–5 µm'],
      ['Núcleo', 'Verdadero, con envoltura nuclear', 'No tiene; ADN en el nucleoide'],
      ['Material genético', 'ADN lineal en varios cromosomas, con histonas', 'Un cromosoma circular + plásmidos'],
      ['Orgánulos membranosos', 'Sí: RE, Golgi, mitocondrias, lisosomas…', 'No'],
      ['Ribosomas', '80S (60S + 40S)', '70S (50S + 30S)'],
      ['Pared celular', 'Solo en plantas (celulosa) y hongos (quitina)', 'Casi siempre (peptidoglucano)'],
      ['Citoesqueleto', 'Complejo: microtúbulos, actina y filamentos intermedios', 'Simple (proteínas FtsZ, MreB)'],
      ['Flagelos', 'Con microtúbulos 9 + 2; se agitan', 'De flagelina; giran como una hélice'],
      ['Respiración celular', 'En las mitocondrias', 'En la membrana plasmática'],
      ['División', 'Mitosis y meiosis', 'Fisión binaria'],
      ['Organismos', 'Animales, plantas, hongos y protistas', 'Bacterias y arqueas'],
    ],
    same: '<b>En común:</b> ambas tienen membrana plasmática, citoplasma, ribosomas y ADN como material genético; usan el mismo código genético y el ATP como moneda de energía.',
  };
  var PRES = {
    membrana: 'Todas las células', citoplasma: 'Todas las células', ribosomas: 'Todas las células',
    pared: 'Procariotas, plantas y hongos', capsula: 'Muchas bacterias', cilios: 'Algunas eucariotas',
    centrosoma: 'Células animales', flagelo: 'Procariotas (distinto del eucariota)', pili: 'Muchas bacterias',
    plasmidos: 'Procariotas (y levaduras)', inclusiones: 'Procariotas', nucleoide: 'Procariotas',
  };
  window.CELULA_DATOS = { INFO: INFO, CMP: CMP, PRES: PRES };
})();
