/* Textos compartidos por celula.html (3D) y celula2d.html (2D):
   cada estructura con su nombre, color, descripción, funciones y dato curioso.
   Revisados con las fuentes listadas en FUENTES (al final del archivo). */
(function () {
  var INFO = {
    euk: {
    basis: 'Alberts y col., Molecular Biology of the Cell, caps. 1 y 12 (compartimentos celulares); OpenStax Biology 2e, fig. 4.8 (célula animal).',
      kicker: 'Célula animal', title: 'Célula eucariota', color: '#5ec8ff', umPerUnit: 2.0,
      badge: ['Célula eucariota animal', 'Modelo esquemático · proporciones aproximadas'],
      desc: 'Tiene un núcleo verdadero rodeado por una envoltura y un sistema de orgánulos membranosos que se reparten el trabajo, como una fábrica con departamentos. Animales, plantas, hongos y protistas están formados por este tipo de célula.',
      facts: [['Tamaño', '10–100 µm'], ['Núcleo', 'Sí, con envoltura'], ['ADN', 'Lineal, con histonas'], ['Ribosomas', '80S'], ['Orgánulos', 'Con membrana'], ['División', 'Mitosis (meiosis para gametos)']],
      parts: [
        { id: 'membrana', name: 'Membrana plasmática', color: '#5ec8ff', cat: 'Membrana', size: 'Bicapa ≈ 5 nm; con proteínas, 7–10 nm', detail: 'mem',
          desc: 'Bicapa de fosfolípidos con proteínas, colesterol y glúcidos (glucocáliz) que envuelve a la célula. Según el modelo de mosaico fluido, sus componentes se desplazan lateralmente.',
          fn: ['Permeabilidad selectiva: controla qué entra y qué sale.', 'Transporte pasivo y activo mediante canales, transportadores y bombas.', 'Reconoce señales químicas gracias a sus receptores.', 'Endocitosis y exocitosis de moléculas grandes.'],
          fact: 'Es tan delgada que harían falta unas 10.000 membranas apiladas para igualar el grosor de una hoja de papel.' },
        { id: 'citoplasma', name: 'Citoplasma', color: '#7fd4ff', cat: 'Medio interno', size: 'El citosol ocupa ≈ 50 % del volumen',
          desc: 'Espacio entre la membrana y el núcleo. Está formado por el citosol —un gel acuoso rico en proteínas, iones y metabolitos— y los orgánulos suspendidos en él. Las partículas en movimiento representan las corrientes citoplasmáticas.',
          fn: ['Sede de la glucólisis y de muchas reacciones metabólicas.', 'Medio de transporte de sustancias.', 'Almacena reservas como glucógeno y gotas de lípidos.'],
          fact: 'El citosol tiene entre 70 y 80 % de agua, pero está tan lleno de proteínas que se comporta más como un gel que como un líquido.' },
        { id: 'nucleo', name: 'Núcleo', color: '#a46cf0', cat: 'Orgánulo · doble membrana', size: '5–10 µm de diámetro', detail: 'nuc',
          desc: 'El centro de control de la célula. Guarda el ADN y regula qué genes se expresan, cuándo y en qué cantidad.',
          fn: ['Almacena y protege la información genética.', 'Transcripción: copia los genes a ARN mensajero.', 'Replica el ADN antes de la división celular.'],
          fact: 'Si se estirara el ADN de un solo núcleo humano mediría unos 2 metros de largo.' },
        { id: 'envoltura', name: 'Envoltura nuclear y poros', short: 'Envoltura nuclear', color: '#d2a8ff', cat: 'Doble membrana', size: 'Poros de ≈ 120 nm', detail: 'nuc',
          desc: 'Doble membrana que rodea al núcleo. La membrana externa se continúa con el retículo endoplasmático rugoso y, como él, tiene ribosomas adheridos. Está atravesada por miles de complejos de poro nuclear.',
          fn: ['Separa el material genético del citoplasma.', 'Los poros regulan la salida de ARN y la entrada de proteínas.', 'Sostiene la cromatina mediante la lámina nuclear.'],
          fact: 'Un núcleo de mamífero tiene entre 2.000 y 4.000 poros, y cada uno puede realizar hasta unos 1.000 transportes por segundo.' },
        { id: 'nucleolo', name: 'Nucléolo', color: '#6a5dff', cat: 'Región sin membrana', size: '1–2 µm',
          desc: 'Región densa del núcleo, sin membrana, donde se transcriben los genes del ARN ribosómico.',
          fn: ['Sintetiza el ARN ribosómico (ARNr).', 'Ensambla las subunidades de los ribosomas.', 'Participa en la respuesta celular al estrés.'],
          fact: 'Las células que fabrican muchas proteínas, como las del páncreas, tienen nucléolos grandes y a veces varios.' },
        { id: 'cromatina', name: 'Cromatina', color: '#9a5ae6', cat: 'ADN + proteínas', size: 'Cadenas de nucleosomas de 5–24 nm',
          desc: 'Complejo de ADN e histonas que llena el núcleo. Puede estar laxa (eucromatina, activa) o compacta (heterocromatina, junto a la envoltura y al nucléolo) y se condensa en cromosomas durante la división. En células vivas forma cadenas flexibles de nucleosomas, no la clásica “fibra de 30 nm” de los libros antiguos.',
          fn: ['Empaqueta el ADN dentro del núcleo.', 'Regula el acceso a los genes (epigenética).', 'Forma los cromosomas en la mitosis.'],
          fact: 'El ADN se enrolla en "carretes" de histonas llamados nucleosomas, como cuentas de un collar.' },
        { id: 'rer', name: 'Retículo endoplasmático rugoso', short: 'RE rugoso', color: '#f07ca0', cat: 'Orgánulo · membrana simple', size: 'Hasta 50 % de las membranas',
          desc: 'Red de sacos aplanados (cisternas) cubiertos de ribosomas y unida a la envoltura nuclear. Esos ribosomas le dan su aspecto "rugoso".',
          fn: ['Síntesis de proteínas de secreción y de membrana.', 'Plegamiento y control de calidad de proteínas.', 'Inicio de la glicosilación.'],
          fact: 'Es muy abundante en células secretoras, como las que producen anticuerpos o enzimas digestivas.' },
        { id: 'rel', name: 'Retículo endoplasmático liso', short: 'RE liso', color: '#c6e05f', cat: 'Orgánulo · membrana simple', size: 'Túbulos de 30–60 nm',
          desc: 'Red de túbulos interconectados sin ribosomas, en continuidad con el RE rugoso.',
          fn: ['Síntesis de lípidos, fosfolípidos y hormonas esteroideas.', 'Detoxificación de fármacos y venenos (sobre todo en el hígado).', 'Almacena y libera calcio (Ca²⁺).'],
          fact: 'En las células musculares se llama retículo sarcoplásmico, y el calcio que libera dispara cada contracción.' },
        { id: 'golgi', name: 'Aparato de Golgi', color: '#ff9b45', cat: 'Orgánulo · membrana simple', size: '1–3 µm', detail: 'golgi',
          desc: 'Pila de cisternas aplanadas con una cara cis, que recibe material del RE, y una cara trans, que despacha vesículas. Funciona como el "correo" de la célula.',
          fn: ['Modifica proteínas y lípidos (glicosilación).', 'Clasifica y empaqueta moléculas en vesículas.', 'Forma lisosomas y vesículas de secreción.'],
          fact: 'Lo describió Camillo Golgi en 1898 con una tinción de plata; durante décadas se dudó de que existiera.' },
        { id: 'mitocondrias', name: 'Mitocondrias', color: '#e5484d', cat: 'Orgánulo · doble membrana', size: '0,5–1 µm de ancho × 1–4 µm', detail: 'mito',
          desc: 'Orgánulos con doble membrana: la interna se pliega en crestas que aumentan su superficie. Tienen ADN y ribosomas propios.',
          fn: ['Respiración celular: producen la mayor parte del ATP.', 'Ciclo de Krebs en la matriz; cadena respiratoria y ATP sintasa en la membrana interna (crestas).', 'Regulan el calcio y la muerte celular programada (apoptosis).'],
          fact: 'Descienden de bacterias que fueron "adoptadas" por otra célula hace más de 1.500 millones de años (teoría endosimbiótica).' },
        { id: 'ribosomas', name: 'Ribosomas (80S)', short: 'Ribosomas', color: '#5b60ff', cat: 'Sin membrana', size: '25–30 nm',
          desc: 'Complejos de ARN ribosómico y proteínas formados por dos subunidades (60S + 40S). Pueden estar libres en el citosol, agrupados en polisomas, o unidos al RE rugoso.',
          fn: ['Traducen el ARN mensajero en proteínas.', 'Los libres fabrican proteínas para el citosol.', 'Los unidos al RER fabrican proteínas de secreción y de membrana.'],
          fact: 'Una sola célula puede tener varios millones de ribosomas trabajando a la vez.' },
        { id: 'lisosomas', name: 'Lisosomas', color: '#ffd166', cat: 'Orgánulo · membrana simple', size: '0,1–1,2 µm',
          desc: 'Vesículas con unas 60 enzimas digestivas distintas (hidrolasas ácidas) que trabajan en un interior ácido, con pH cercano a 4,5–5. Una bomba de protones (V-ATPasa) de su membrana mantiene esa acidez.',
          fn: ['Digestión intracelular de macromoléculas.', 'Autofagia: reciclan orgánulos viejos o dañados.', 'Degradan bacterias y partículas fagocitadas.'],
          fact: 'Su pH ácido es una medida de seguridad: si sus enzimas escapan al citosol (pH 7,2) casi no funcionan.' },
        { id: 'peroxisomas', name: 'Peroxisomas', color: '#5cd18a', cat: 'Orgánulo · membrana simple', size: '0,1–1 µm',
          desc: 'Vesículas con enzimas oxidativas como la catalasa. En muchos mamíferos (no en los humanos) muestran un núcleo cristalino de urato oxidasa.',
          fn: ['Degradan ácidos grasos de cadena muy larga.', 'Descomponen el peróxido de hidrógeno (H₂O₂) en agua y oxígeno.', 'Participan en la síntesis de lípidos de la mielina.'],
          fact: 'La catalasa es una de las enzimas más rápidas que existen: procesa millones de moléculas de H₂O₂ por segundo.' },
        { id: 'vesiculas', name: 'Vesículas de transporte', short: 'Vesículas', color: '#bfe4ff', cat: 'Membrana simple', size: '50–200 nm',
          desc: 'Pequeñas esferas de membrana que llevan carga entre el RE, el Golgi, la membrana y los lisosomas. En el modelo se las ve viajar por la célula.',
          fn: ['Transporte del RE al Golgi.', 'Secreción hacia el exterior por exocitosis.', 'Captación de material por endocitosis.'],
          fact: 'Las proteínas motoras cinesina y dineína "caminan" sobre los microtúbulos con pasos de 8 nm.' },
        { id: 'centrosoma', name: 'Centrosoma y centriolos', short: 'Centrosoma', color: '#ff4fa3', cat: 'Sin membrana', size: 'Centriolos de ≈ 0,2 × 0,5 µm',
          desc: 'Par de centriolos perpendiculares, cada uno con 9 tripletes de microtúbulos, rodeados de material pericentriolar.',
          fn: ['Principal centro organizador de microtúbulos.', 'Forma el huso mitótico durante la división.', 'Origina los cuerpos basales de cilios y flagelos.'],
          fact: 'Es típico de las células animales: la mayoría de las células vegetales no tiene centriolos.' },
        { id: 'citoesqueleto', name: 'Citoesqueleto', color: '#8fd8ff', cat: 'Red de proteínas', size: '7–25 nm de grosor',
          desc: 'Red dinámica de microtúbulos (25 nm), filamentos intermedios (10 nm) y microfilamentos de actina (7 nm). Los destellos que recorren los microtúbulos representan el transporte de carga.',
          fn: ['Da forma y resistencia mecánica a la célula.', 'Sirve de vía para el transporte de vesículas y orgánulos.', 'Permite el movimiento celular y la división.'],
          fact: 'Los microtúbulos crecen y se desarman continuamente: es lo que se llama inestabilidad dinámica.' },
        { id: 'cilios', name: 'Cilios', color: '#d6ecff', cat: 'Prolongación de membrana', size: '0,25 µm × 5–10 µm',
          desc: 'Prolongaciones móviles sostenidas por un axonema de microtúbulos en disposición 9 + 2, que nace de un cuerpo basal (un centriolo modificado) bajo la membrana. Baten coordinados en ondas metacrónicas.',
          fn: ['Desplazan líquidos y partículas, como el moco en las vías respiratorias.', 'Permiten nadar a algunos protistas.', 'El cilio primario funciona como antena sensorial.'],
          fact: 'Cada célula de la tráquea tiene unos 200 cilios que baten entre 10 y 20 veces por segundo.' },
      ],
    },
    pro: {
    basis: 'Alberts y col., cap. 1; Cooper, The Cell, cap. 1; OpenStax Biology 2e, fig. 4.5 (célula procariota).',
      kicker: 'Bacilo Gram negativo', title: 'Célula procariota', color: '#4fd38b', umPerUnit: 0.26,
      badge: ['Célula procariota · bacilo Gram negativo', 'Modelo esquemático · proporciones aproximadas'],
      desc: 'No tiene núcleo ni, en general, orgánulos membranosos: su ADN está libre en el citoplasma, en el nucleoide. Son las células más antiguas (unos 3.500 millones de años) y las más abundantes del planeta: bacterias y arqueas. El modelo muestra un bacilo Gram negativo, como E. coli.',
      facts: [['Tamaño', '0,5–5 µm'], ['Núcleo', 'No (nucleoide)'], ['ADN', 'Casi siempre circular + plásmidos'], ['Ribosomas', '70S'], ['Orgánulos', 'Sin membrana'], ['División', 'Fisión binaria']],
      parts: [
        { id: 'capsula', name: 'Cápsula', color: '#2bb673', cat: 'Envoltura externa', size: '0,2–1 µm',
          desc: 'Capa gelatinosa de polisacáridos (a veces de proteínas) que rodea a muchas bacterias por fuera de la pared.',
          fn: ['Protege de la desecación y de la fagocitosis.', 'Facilita la adhesión y la formación de biopelículas.', 'Es un factor de virulencia en patógenos como el neumococo.'],
          fact: 'En 1928 Griffith descubrió la "transformación" bacteriana comparando neumococos con y sin cápsula.' },
        { id: 'pared', name: 'Pared celular y membrana externa', short: 'Pared celular', color: '#e05a4b', cat: 'Envoltura Gram negativa', size: 'Peptidoglucano: 2–7 nm (Gram −) o 20–80 nm (Gram +)', detail: 'flag',
          desc: 'Malla de peptidoglucano (mureína) por fuera de la membrana. En las Gram negativas, como este bacilo, es una capa delgada dentro del periplasma, cubierta por una membrana externa con lipopolisacárido (LPS). Las Gram positivas no tienen membrana externa, pero su peptidoglucano es mucho más grueso.',
          fn: ['Da forma a la célula (bacilo, coco, espirilo).', 'Resiste la presión osmótica y evita que la célula estalle.', 'Es el blanco de antibióticos como la penicilina.'],
          fact: 'La tinción de Gram, inventada en 1884, clasifica a las bacterias justamente según esta pared.' },
        { id: 'membrana', name: 'Membrana plasmática', color: '#f4d03f', cat: 'Membrana interna', size: '7–8 nm', detail: 'flag',
          desc: 'Bicapa lipídica con proteínas, similar a la eucariota. Como no hay mitocondrias, en ella ocurren la respiración y la síntesis de ATP.',
          fn: ['Transporte selectivo de nutrientes e iones.', 'Cadena respiratoria y ATP sintasa.', 'Anclaje del motor flagelar y síntesis de la pared.'],
          fact: 'El flujo de protones a través de esta membrana es lo que hace girar el motor del flagelo.' },
        { id: 'citoplasma', name: 'Citoplasma', color: '#5fa8e8', cat: 'Medio interno', size: '≈ 80 % agua',
          desc: 'Citosol sin compartimentos membranosos internos, muy concentrado en proteínas, ribosomas y metabolitos.',
          fn: ['Sede del metabolismo (glucólisis, biosíntesis).', 'Contiene el nucleoide, los ribosomas y las inclusiones.', 'Allí la transcripción y la traducción ocurren a la vez.'],
          fact: 'En las bacterias un gen puede empezar a traducirse mientras todavía se está transcribiendo.' },
        { id: 'nucleoide', name: 'Nucleoide (cromosoma)', short: 'Nucleoide', color: '#e63946', cat: 'Región sin membrana', size: 'ADN de ≈ 1,5 mm',
          desc: 'Región irregular donde está el cromosoma bacteriano: una única molécula de ADN circular, superenrollada y sin histonas verdaderas.',
          fn: ['Contiene los genes esenciales de la célula.', 'Se replica y se reparte durante la fisión binaria.', 'Lo organizan proteínas asociadas como HU y H-NS.'],
          fact: 'El cromosoma de E. coli tiene 4,6 millones de pares de bases y mide 1,5 mm: ¡unas 700 veces el largo de la bacteria!' },
        { id: 'plasmidos', name: 'Plásmidos', color: '#7bed9f', cat: 'ADN extracromosómico', size: 'De ≈ 1 kb a más de 1 Mb',
          desc: 'Pequeñas moléculas de ADN circular, independientes del cromosoma, que se replican por su cuenta.',
          fn: ['Portan genes accesorios (resistencia a antibióticos, toxinas).', 'Se transfieren entre bacterias por conjugación.', 'Se usan como vectores en ingeniería genética.'],
          fact: 'Gracias a los plásmidos la resistencia a antibióticos puede pasar de una especie bacteriana a otra.' },
        { id: 'ribosomas', name: 'Ribosomas (70S)', short: 'Ribosomas', color: '#7a80d8', cat: 'Sin membrana', size: '≈ 20 nm',
          desc: 'Más pequeños que los eucariotas y formados por subunidades 50S y 30S. Están dispersos por todo el citoplasma.',
          fn: ['Traducen el ARNm en proteínas.', 'Pueden traducir mientras el ARNm se sintetiza.', 'Son blanco de antibióticos como tetraciclinas y estreptomicina.'],
          fact: 'Una bacteria de crecimiento rápido puede tener hasta 70.000 ribosomas.' },
        { id: 'inclusiones', name: 'Inclusiones', color: '#f4a261', cat: 'Gránulos de reserva', size: '0,1–1 µm',
          desc: 'Depósitos de sustancias de reserva en el citoplasma, como glucógeno, polifosfato (volutina) o polihidroxibutirato (PHB).',
          fn: ['Almacenan carbono, energía o fosfato.', 'Permiten sobrevivir en épocas de escasez.', 'Los magnetosomas (cristales de magnetita rodeados de membrana) orientan a algunas bacterias.'],
          fact: 'El PHB que acumulan algunas bacterias se usa para fabricar plásticos biodegradables.' },
        { id: 'pili', name: 'Pili y fimbrias', short: 'Pili', color: '#5fd39a', cat: 'Apéndices proteicos', size: '2–10 nm × hasta 2 µm',
          desc: 'Filamentos de pilina más finos y cortos que el flagelo. Las fimbrias son numerosas; el pilus sexual, largo y único, se ve sobresaliendo del resto.',
          fn: ['Adhesión a superficies y a células del huésped.', 'Conjugación: el pilus sexual une dos bacterias para transferir ADN.', 'Algunos permiten moverse a "tirones" (twitching).'],
          fact: 'Los pili tipo IV se retraen con una fuerza enorme para su tamaño: más de 100 piconewtons.' },
        { id: 'flagelo', name: 'Flagelo', color: '#27a065', cat: 'Apéndice de locomoción', size: '≈ 20 nm × 5–10 µm', detail: 'flag',
          desc: 'Filamento helicoidal de flagelina unido por un gancho a un motor rotatorio incrustado en la membrana y la pared.',
          fn: ['Propulsa a la bacteria girando como una hélice.', 'Permite la quimiotaxis: nadar hacia nutrientes o lejos de tóxicos.', 'El motor puede invertir el giro para cambiar de dirección.'],
          fact: 'En E. coli el motor da más de 100 vueltas por segundo; en Vibrio, impulsado por sodio, llega a 1.700 (≈ 100.000 rpm). Puede invertir el giro en milisegundos.' },
      ],
    },
  };
  var CMP = {
    rows: [
      ['Tamaño típico', '10–100 µm', '0,5–5 µm'],
      ['Núcleo', 'Verdadero, con envoltura nuclear', 'No tiene; ADN en el nucleoide'],
      ['Material genético', 'ADN lineal en varios cromosomas, con histonas', 'Un cromosoma circular + plásmidos'],
      ['Orgánulos membranosos', 'Sí: RE, Golgi, mitocondrias, lisosomas…', 'No'],
      ['Ribosomas', '80S (60S + 40S)', '70S (50S + 30S)'],
      ['Pared celular', 'En plantas y algas (celulosa) y hongos (quitina); no en animales', 'Casi siempre (peptidoglucano)'],
      ['Citoesqueleto', 'Complejo: microtúbulos, actina y filamentos intermedios', 'Simple (proteínas FtsZ, MreB)'],
      ['Flagelos', 'Con microtúbulos 9 + 2; se agitan', 'De flagelina; giran como una hélice'],
      ['Respiración celular', 'En las mitocondrias', 'En la membrana plasmática'],
      ['División', 'Mitosis (y meiosis para formar gametos)', 'Fisión binaria'],
      ['Organismos', 'Animales, plantas, hongos y protistas', 'Bacterias y arqueas'],
    ],
    same: '<b>En común:</b> ambas tienen membrana plasmática, citoplasma, ribosomas y ADN como material genético; usan el mismo código genético y el ATP como moneda de energía.',
  };
  var PRES = {
    membrana: 'Todas las células', citoplasma: 'Todas las células', ribosomas: 'Todas las células',
    pared: 'Procariotas, plantas y hongos', capsula: 'Muchas bacterias', cilios: 'Algunas eucariotas',
    centrosoma: 'Células animales', flagelo: 'Procariotas (distinto del eucariota)', pili: 'Muchas bacterias',
    plasmidos: 'Procariotas (y levaduras)', inclusiones: 'Procariotas', nucleoide: 'Procariotas',
  };

  /* Estructura interna de los orgánulos principales (vistas de detalle del modelo 3D).
     parent: célula a la que pertenecen · from: estructura de esa célula desde la que se abren */
  INFO.mito = {
    basis: 'Alberts y col., cap. 14 (mitocondrias); OpenStax Biology 2e, fig. 4.11; Kühlbrandt (2015); revisión sobre la arquitectura de las crestas (Membranes, 2021); Anderson y col. (1981).',
    parent: 'euk', from: 'mitocondrias', kicker: 'Estructura interna', title: 'Mitocondria', color: '#e5484d', umPerUnit: 0.14,
    badge: ['Mitocondria en corte', 'Modelo esquemático · proporciones aproximadas'],
    desc: 'Corte longitudinal de una mitocondria. Dos membranas delimitan dos compartimentos: el espacio intermembrana y la matriz. La membrana interna se pliega en crestas, donde la cadena respiratoria y la ATP sintasa producen la mayor parte del ATP de la célula.',
    facts: [['Ancho', '0,5–1 µm'], ['Membranas', '2: externa e interna'], ['ADN propio', '16.569 pb (humano)'], ['Genes', '37'], ['Ribosomas', '55S'], ['Función', 'Respiración celular']],
    parts: [
      { id: 'membext', name: 'Membrana externa', color: '#ff7b7f', cat: 'Membrana', size: '≈ 7 nm',
        desc: 'Lisa y bastante permeable: tiene muchas porinas (VDAC), canales por los que pasan iones y moléculas pequeñas de hasta unos 5.000 Da.',
        fn: ['Separa la mitocondria del citosol.', 'Deja pasar metabolitos pequeños a través de las porinas.', 'Importa proteínas mediante el complejo TOM.'],
        fact: 'Casi todas las proteínas de la mitocondria se fabrican en el citosol y entran por los complejos TOM y TIM.' },
      { id: 'intermem', name: 'Espacio intermembrana', color: '#ffc9a8', cat: 'Compartimento', size: 'Pocos nanómetros de ancho',
        desc: 'Espacio estrecho entre las dos membranas. Sus moléculas pequeñas son parecidas a las del citosol, y en él se acumulan los protones que bombea la cadena respiratoria.',
        fn: ['Acumula protones (H⁺) y crea el gradiente que impulsa a la ATP sintasa.', 'Contiene el citocromo c, que lleva electrones del complejo III al IV.'],
        fact: 'Si el citocromo c sale al citosol, dispara la apoptosis (muerte celular programada).' },
      { id: 'membint', name: 'Membrana interna', color: '#ffc2cc', cat: 'Membrana', size: '≈ 7 nm',
        desc: 'Muy impermeable, incluso a los iones: solo deja pasar lo que transportan sus proteínas. Es rica en cardiolipina, un lípido casi exclusivo de mitocondrias y bacterias.',
        fn: ['Mantiene el gradiente de protones.', 'Intercambia ATP por ADP y transporta otros metabolitos.', 'Importa proteínas mediante el complejo TIM.'],
        fact: 'Es una de las membranas con más proteínas: cerca de tres cuartos de su masa.' },
      { id: 'crestas', name: 'Crestas', color: '#ff8fa0', cat: 'Pliegues de la membrana interna', size: 'Varían según el tejido',
        desc: 'Pliegues de la membrana interna unidos al resto de ella por cuellos estrechos (uniones de las crestas). Multiplican la superficie disponible para producir ATP.',
        fn: ['Alojan la cadena respiratoria y la ATP sintasa.', 'Su forma la sostienen los dímeros de ATP sintasa y el complejo MICOS.'],
        fact: 'Las células que gastan mucha energía, como las del músculo cardíaco, tienen mitocondrias repletas de crestas.' },
      { id: 'matriz', name: 'Matriz mitocondrial', short: 'Matriz', color: '#c23a55', cat: 'Compartimento interno', size: 'Muy concentrada en enzimas',
        desc: 'Interior de la mitocondria: un gel muy denso en enzimas. Contiene el ADN mitocondrial, los mitorribosomas y gránulos de calcio.',
        fn: ['Ciclo de Krebs (ácido cítrico).', 'Oxidación de los ácidos grasos (β-oxidación).', 'Replicación y expresión del ADN mitocondrial.'] },
      { id: 'cadena', name: 'Cadena respiratoria', color: '#ffd166', cat: 'Complejos proteicos I–IV', size: 'Complejos de 10–20 nm',
        desc: 'Complejos proteicos (I, II, III y IV) incrustados en la membrana interna, sobre todo en las crestas. Pasan los electrones del NADH y el FADH₂ hasta el oxígeno, que se reduce a agua.',
        fn: ['Transporta electrones hasta el O₂.', 'Los complejos I, III y IV bombean protones al espacio intermembrana.'],
        fact: 'Por eso respiramos oxígeno: es el aceptor final de esos electrones.' },
      { id: 'atp', name: 'ATP sintasa', color: '#5ec8ff', cat: 'Motor rotatorio', size: 'Cabeza F₁ de ≈ 10 nm',
        desc: 'Turbina molecular: los protones que vuelven a la matriz hacen girar su rotor, y la cabeza F₁, que asoma hacia la matriz, une ADP y fosfato para formar ATP. Forma filas de dímeros en los bordes de las crestas.',
        fn: ['Produce la mayor parte del ATP celular.', 'Sus dímeros curvan la membrana en el borde de las crestas.'],
        fact: 'Cada vuelta completa del rotor produce 3 moléculas de ATP.' },
      { id: 'adnmt', name: 'ADN mitocondrial', color: '#b98af0', cat: 'Material genético propio', size: '16.569 pares de bases',
        desc: 'Molécula de ADN circular, con varias copias por mitocondria agrupadas en nucleoides. En humanos tiene 37 genes: 13 de proteínas de la cadena respiratoria y la ATP sintasa, 22 de ARNt y 2 de ARNr.',
        fn: ['Codifica proteínas esenciales para la respiración.', 'Se hereda casi siempre por vía materna.'],
        fact: 'Es un rastro de su origen bacteriano: por eso es circular, como el cromosoma de las bacterias.' },
      { id: 'mitorrib', name: 'Mitorribosomas', color: '#7a80ff', cat: 'Sin membrana', size: '55S (39S + 28S)',
        desc: 'Ribosomas propios de la mitocondria, más parecidos a los bacterianos que a los del citosol. Fabrican las 13 proteínas codificadas por el ADN mitocondrial.',
        fn: ['Traducen los ARNm mitocondriales.', 'Se asocian a la membrana interna para insertar allí sus proteínas.'],
        fact: 'Algunos antibióticos que frenan los ribosomas bacterianos también pueden afectar a los mitorribosomas.' },
    ],
  };
  INFO.nuc = {
    basis: 'Alberts y col., caps. 4 (cromatina) y 12 (envoltura y poros nucleares); Ou y col. (2017).',
    parent: 'euk', from: 'nucleo', kicker: 'Estructura interna', title: 'Núcleo', color: '#a46cf0', umPerUnit: 1.0,
    badge: ['Núcleo en corte', 'Modelo esquemático · proporciones aproximadas'],
    desc: 'Corte del núcleo. La envoltura nuclear son dos membranas separadas por el espacio perinuclear, atravesadas por los complejos del poro y sostenidas por la lámina nuclear. Adentro, la cromatina ocupa territorios y el nucléolo fabrica ribosomas.',
    facts: [['Diámetro', '5–10 µm'], ['Membranas', '2 (envoltura nuclear)'], ['Poros', '2.000–4.000'], ['ADN (humano)', '≈ 2 m por núcleo'], ['Cromosomas', '46 (humano)'], ['Unidad básica', 'Nucleosoma']],
    parts: [
      { id: 'membext', name: 'Membrana nuclear externa', short: 'Membrana externa', color: '#d2a8ff', cat: 'Membrana', size: '≈ 7 nm',
        desc: 'Se continúa directamente con el retículo endoplasmático rugoso y, como él, tiene ribosomas adheridos en su cara citosólica.',
        fn: ['Fabrica proteínas con sus ribosomas, como el RE rugoso.', 'Conecta el núcleo con el citoesqueleto (complejos LINC).'] },
      { id: 'perinuc', name: 'Espacio perinuclear', color: '#f3e3ff', cat: 'Compartimento', size: '≈ 20–50 nm',
        desc: 'Espacio entre las dos membranas nucleares. Se continúa con el interior (luz) del retículo endoplasmático.',
        fn: ['Comunica con la luz del RE.', 'Almacena calcio, igual que el RE.'] },
      { id: 'membint', name: 'Membrana nuclear interna', short: 'Membrana interna', color: '#b98af0', cat: 'Membrana', size: '≈ 7 nm',
        desc: 'Tiene proteínas propias que se unen a la lámina nuclear y a la cromatina.',
        fn: ['Ancla la lámina y la cromatina.', 'Ayuda a ubicar los genes dentro del núcleo.'] },
      { id: 'poros', name: 'Complejos del poro nuclear', short: 'Poros nucleares', color: '#ffe08a', cat: 'Complejo proteico', size: '≈ 120 nm de diámetro',
        desc: 'Grandes estructuras de unas 30 proteínas distintas (nucleoporinas) dispuestas con simetría de 8. Tienen filamentos hacia el citoplasma y una “canasta” hacia el núcleo.',
        fn: ['Dejan pasar libremente las moléculas pequeñas.', 'Importan proteínas con señal de localización nuclear.', 'Exportan ARNm y subunidades de ribosomas.'],
        fact: 'Cada poro puede realizar hasta unos 1.000 transportes por segundo.' },
      { id: 'lamina', name: 'Lámina nuclear', color: '#8fd8ff', cat: 'Filamentos intermedios', size: '≈ 15 nm de espesor',
        desc: 'Red de filamentos intermedios (láminas A, B y C) que tapiza la cara interna de la envoltura.',
        fn: ['Da forma y resistencia al núcleo.', 'Ancla la heterocromatina.', 'Se desarma durante la mitosis.'],
        fact: 'Una mutación de la lámina A causa la progeria, un envejecimiento acelerado.' },
      { id: 'nucleolo', name: 'Nucléolo', color: '#6a5dff', cat: 'Región sin membrana', size: '1–2 µm',
        desc: 'Región densa sin membrana con tres zonas: centros fibrilares (genes del ARNr), componente fibrilar denso (donde se transcriben y procesan) y componente granular (donde se arman las subunidades del ribosoma).',
        fn: ['Transcribe y procesa el ARN ribosómico.', 'Ensambla las subunidades de los ribosomas.'] },
      { id: 'eucro', name: 'Eucromatina', color: '#d6b8ff', cat: 'ADN + histonas (laxa)', size: 'Cadenas de nucleosomas de 5–24 nm',
        desc: 'Cromatina poco compactada y accesible a la maquinaria de transcripción: allí están los genes activos.',
        fn: ['Permite leer los genes (transcripción).', 'Ocupa el interior del núcleo.'] },
      { id: 'hetero', name: 'Heterocromatina', color: '#5a2a9e', cat: 'ADN + histonas (compacta)', size: 'Grumos densos',
        desc: 'Cromatina muy compactada y en general silenciosa. Se acumula junto a la lámina nuclear y alrededor del nucléolo.',
        fn: ['Mantiene apagados los genes que la célula no usa.', 'Protege regiones repetitivas como los centrómeros.'] },
      { id: 'nucleoplasma', name: 'Nucleoplasma', color: '#9a7ad6', cat: 'Medio interno', size: '—',
        desc: 'Medio acuoso del núcleo, con enzimas, nucleótidos, ARN y factores de transcripción.',
        fn: ['Medio donde ocurren la replicación y la transcripción.'] },
      { id: 'rer', name: 'Retículo endoplasmático rugoso', short: 'RE rugoso', color: '#f07ca0', cat: 'Continuo con la envoltura', size: 'Cisternas de ≈ 50 nm',
        desc: 'La membrana nuclear externa se continúa con las cisternas del RE rugoso: forman un único sistema de membranas.',
        fn: ['Recibe proteínas recién fabricadas en su luz.'] },
    ],
  };
  INFO.mem = {
    basis: 'Singer y Nicolson (1972); Alberts y col., cap. 10 (estructura de la membrana).',
    parent: 'euk', from: 'membrana', kicker: 'Estructura interna', title: 'Membrana plasmática', color: '#5ec8ff', umPerUnit: 0.0012,
    badge: ['Membrana plasmática · mosaico fluido', 'Modelo esquemático · proporciones aproximadas'],
    desc: 'Fragmento de membrana según el modelo de mosaico fluido (Singer y Nicolson, 1972): una bicapa de lípidos en la que se mueven proteínas. Arriba está el medio extracelular, con el glucocáliz; abajo, el citosol y la corteza de actina.',
    facts: [['Bicapa', '≈ 5 nm'], ['Proteínas', '≈ 50 % de la masa'], ['Lípidos', 'Fosfolípidos, colesterol, glucolípidos'], ['Azúcares', 'Solo en la cara externa'], ['Modelo', 'Mosaico fluido (1972)'], ['Capas', 'Asimétricas']],
    parts: [
      { id: 'cabezas', name: 'Cabezas hidrofílicas', color: '#5ec8ff', cat: 'Fosfolípidos', size: '≈ 1 nm',
        desc: 'Extremos polares de los fosfolípidos (fosfato unido a colina, serina, etanolamina…). Miran hacia el agua: el medio extracelular arriba y el citosol abajo.',
        fn: ['Forman las dos caras de la membrana en contacto con el agua.', 'La fosfatidilserina queda en la cara citosólica; si aparece afuera, es señal de apoptosis.'] },
      { id: 'colas', name: 'Colas hidrofóbicas', color: '#ffd27a', cat: 'Ácidos grasos', size: 'Núcleo de ≈ 3–4 nm',
        desc: 'Dos cadenas de ácidos grasos por fosfolípido que se esconden del agua en el centro de la bicapa. Los dobles enlaces cis les dan codos que aumentan la fluidez.',
        fn: ['Forman la barrera que frena el paso de iones y moléculas polares.', 'Su largo y saturación regulan la fluidez.'] },
      { id: 'colesterol', name: 'Colesterol', color: '#fff3b0', cat: 'Lípido esteroide', size: '≈ 2 nm',
        desc: 'Lípido rígido intercalado entre los fosfolípidos. En la membrana plasmática animal puede haber casi una molécula por cada fosfolípido.',
        fn: ['Regula la fluidez de la membrana.', 'Reduce la permeabilidad a moléculas pequeñas.', 'Participa en dominios llamados balsas lipídicas.'] },
      { id: 'integral', name: 'Proteína integral', color: '#ff8fb1', cat: 'Transmembrana', size: '≈ 5–10 nm',
        desc: 'Atraviesa la bicapa, por lo general con hélices α hidrofóbicas. Muchas son receptores, transportadores o moléculas de adhesión.',
        fn: ['Recibe señales (receptores).', 'Transporta sustancias (transportadores y bombas).', 'Une células entre sí y a la matriz extracelular.'] },
      { id: 'canal', name: 'Canal iónico', color: '#7ee0a8', cat: 'Proteína transmembrana', size: 'Poro < 1 nm',
        desc: 'Proteína con un poro acuoso que deja pasar iones específicos (Na⁺, K⁺, Ca²⁺, Cl⁻) a favor de su gradiente. Muchos se abren o cierran según señales eléctricas o químicas.',
        fn: ['Permite los impulsos nerviosos.', 'Regula el volumen y el potencial de la célula.'],
        fact: 'Un canal abierto puede dejar pasar hasta unos 100 millones de iones por segundo.' },
      { id: 'periferica', name: 'Proteína periférica', color: '#c6a0ff', cat: 'Asociada a la membrana', size: 'Variable',
        desc: 'Se une a la superficie de la membrana o a otras proteínas sin atravesar la bicapa.',
        fn: ['Une la membrana con el citoesqueleto.', 'Participa en la transmisión de señales.'] },
      { id: 'glucocaliz', name: 'Glucocáliz', color: '#9ff0c4', cat: 'Glucoproteínas y glucolípidos', size: 'Hasta ≈ 100 nm',
        desc: 'Cadenas de azúcares unidas a proteínas (glucoproteínas) y a lípidos (glucolípidos), siempre del lado externo.',
        fn: ['Reconocimiento entre células.', 'Protección mecánica y química.', 'Adhesión.'],
        fact: 'Los grupos sanguíneos A, B y 0 dependen de los azúcares del glucocáliz de los glóbulos rojos.' },
      { id: 'cortical', name: 'Corteza de actina', color: '#ff8fb8', cat: 'Citoesqueleto', size: 'Filamentos de ≈ 7 nm',
        desc: 'Red de filamentos de actina (y espectrina) unida a la cara interna de la membrana.',
        fn: ['Da forma y resistencia a la superficie celular.', 'Permite la endocitosis y el movimiento celular.'] },
    ],
  };
  INFO.golgi = {
    basis: 'Alberts y col., cap. 13 (tráfico de vesículas y aparato de Golgi).',
    parent: 'euk', from: 'golgi', kicker: 'Estructura interna', title: 'Aparato de Golgi', color: '#ff9b45', umPerUnit: 0.22,
    badge: ['Aparato de Golgi y tráfico de vesículas', 'Modelo esquemático · proporciones aproximadas'],
    desc: 'Pila de cisternas aplanadas con dos caras: la cis, que mira al RE y recibe vesículas COPII, y la trans, que despacha la carga ya modificada. Las proteínas avanzan de cisterna en cisterna mientras sus azúcares se modifican paso a paso.',
    facts: [['Cisternas', '4–6 por pila (a veces más)'], ['Entrada', 'Cara cis'], ['Salida', 'Cara trans'], ['Ubicación', 'Junto al centrosoma'], ['Ida desde el RE', 'Vesículas COPII'], ['Vuelta al RE', 'Vesículas COPI']],
    parts: [
      { id: 're', name: 'RE de transición', color: '#f07ca0', cat: 'Retículo endoplasmático', size: '—',
        desc: 'Sitios del retículo endoplasmático sin ribosomas donde se forman las vesículas que van al Golgi.',
        fn: ['Empaqueta en vesículas las proteínas bien plegadas.'] },
      { id: 'copii', name: 'Vesículas COPII', color: '#7ee0a8', cat: 'Transporte anterógrado', size: '≈ 60–80 nm',
        desc: 'Vesículas cubiertas por la proteína COPII que llevan las proteínas recién hechas del RE hacia el Golgi.',
        fn: ['Transporte del RE al Golgi.'] },
      { id: 'cgn', name: 'Red cis del Golgi', color: '#fff0a0', cat: 'Cara de entrada', size: '—',
        desc: 'Red de túbulos y vesículas fusionadas en la cara cis, la que mira al RE y al núcleo.',
        fn: ['Recibe la carga del RE.', 'Devuelve al RE, en vesículas COPI, las proteínas que se escaparon.'] },
      { id: 'cis', name: 'Cisternas cis', color: '#ffd166', cat: 'Compartimento', size: '≈ 1 µm de ancho',
        desc: 'Primeras cisternas de la pila. Allí empieza la modificación de los azúcares unidos a las proteínas.',
        fn: ['Marcan con manosa-6-fosfato las enzimas destinadas a los lisosomas.', 'Recortan manosas de los oligosacáridos.'] },
      { id: 'medial', name: 'Cisternas mediales', color: '#ffb056', cat: 'Compartimento', size: '≈ 1 µm de ancho',
        desc: 'Cisternas centrales, con enzimas que siguen remodelando los oligosacáridos.',
        fn: ['Quitan más manosas.', 'Agregan N-acetilglucosamina.'] },
      { id: 'trans', name: 'Cisternas trans', color: '#ff8a45', cat: 'Compartimento', size: '≈ 1 µm de ancho',
        desc: 'Últimas cisternas de la pila, donde se completan las modificaciones.',
        fn: ['Agregan galactosa y ácido siálico.', 'Sulfatan algunas proteínas.'] },
      { id: 'tgn', name: 'Red trans del Golgi', color: '#ff6b3d', cat: 'Cara de salida', size: '—',
        desc: 'Red de túbulos en la cara trans que clasifica la carga y la envía en distintas vesículas.',
        fn: ['Separa la carga según su destino: membrana, lisosomas o secreción.'] },
      { id: 'copi', name: 'Vesículas COPI', color: '#8fd8ff', cat: 'Transporte retrógrado', size: '≈ 50–60 nm',
        desc: 'Vesículas cubiertas por COPI que devuelven al RE sus proteínas residentes y mueven material entre cisternas.',
        fn: ['Transporte del Golgi al RE.', 'Transporte entre cisternas.'] },
      { id: 'secretoras', name: 'Vesículas de secreción', color: '#ffc6d8', cat: 'Exocitosis', size: '100 nm a 1 µm',
        desc: 'Llevan proteínas y otras moléculas a la membrana plasmática para liberarlas por exocitosis, de manera continua o cuando llega una señal.',
        fn: ['Secreción de hormonas, enzimas y anticuerpos.', 'Renuevan la membrana plasmática.'] },
      { id: 'clatrina', name: 'Vesículas con clatrina', color: '#c9d7ee', cat: 'Hacia endosomas y lisosomas', size: '≈ 100 nm',
        desc: 'Cubiertas por una red de clatrina con forma de jaula. Llevan las enzimas marcadas con manosa-6-fosfato hacia los endosomas, que luego maduran en lisosomas.',
        fn: ['Entregan hidrolasas a los lisosomas.'] },
    ],
  };
  INFO.flag = {
    basis: 'Berg (2003); Magariyama y col. (1994).',
    parent: 'pro', from: 'flagelo', kicker: 'Estructura interna', title: 'Motor flagelar y envoltura', color: '#27a065', umPerUnit: 0.01,
    badge: ['Motor del flagelo · envoltura Gram negativa', 'Modelo esquemático · proporciones aproximadas'],
    desc: 'Corte de la envoltura de una bacteria Gram negativa, como E. coli, con el motor del flagelo. Es un motor rotatorio verdadero: un rotor gira dentro de anillos fijos, impulsado por el flujo de protones a través de los estatores.',
    facts: [['Diámetro del motor', '≈ 45 nm'], ['Energía', 'Flujo de H⁺ (o Na⁺)'], ['Velocidad (E. coli)', '> 100 vueltas/s'], ['Consumo', '≈ 1.200 H⁺ por vuelta'], ['Proteínas', 'Unas 25 distintas'], ['Giro', 'Horario y antihorario']],
    parts: [
      { id: 'filamento', name: 'Filamento', color: '#27a065', cat: 'Flagelina (FliC)', size: '≈ 20 nm × 5–10 µm',
        desc: 'Tubo helicoidal hueco de miles de subunidades de flagelina. Crece por la punta: las nuevas subunidades viajan por su interior.',
        fn: ['Actúa como hélice al girar.'],
        fact: 'Cuando varios flagelos giran en sentido antihorario forman un haz y la bacteria nada recto; si alguno se invierte, el haz se abre y la bacteria cambia de dirección.' },
      { id: 'gancho', name: 'Gancho', color: '#1d9a68', cat: 'Junta universal (FlgE)', size: '≈ 55 nm de largo',
        desc: 'Tramo corto y flexible que transmite el giro del rotor al filamento, como una junta universal.',
        fn: ['Une la varilla con el filamento.', 'Permite que el filamento gire aunque esté en ángulo.'] },
      { id: 'anilloL', name: 'Anillo L', color: '#ffb056', cat: 'Buje (membrana externa)', size: '≈ 20 nm',
        desc: 'Anillo fijo incrustado en la membrana externa (capa de lipopolisacárido) por el que pasa la varilla.',
        fn: ['Funciona como cojinete de la varilla.'] },
      { id: 'anilloP', name: 'Anillo P', color: '#ff8a45', cat: 'Buje (peptidoglucano)', size: '≈ 20 nm',
        desc: 'Anillo fijo en la capa de peptidoglucano. Junto con el anillo L forma un buje por el que gira la varilla.',
        fn: ['Funciona como cojinete de la varilla.'] },
      { id: 'varilla', name: 'Varilla (eje)', color: '#e9f2ff', cat: 'Eje de transmisión', size: '≈ 7 nm de ancho',
        desc: 'Eje que atraviesa el periplasma y une el rotor con el gancho.',
        fn: ['Transmite el giro del rotor.'] },
      { id: 'anilloMS', name: 'Anillo MS', color: '#ffd84a', cat: 'Rotor (FliF)', size: '≈ 25 nm',
        desc: 'Anillo del rotor incrustado en la membrana interna; es la base sobre la que se arma todo el motor.',
        fn: ['Ancla el rotor a la membrana.', 'Sostiene la varilla y el anillo C.'] },
      { id: 'anilloC', name: 'Anillo C (interruptor)', short: 'Anillo C', color: '#f4a261', cat: 'Rotor (FliG, FliM, FliN)', size: '≈ 45 nm',
        desc: 'Anillo citoplasmático que recibe el empuje de los estatores. Cuando se le une la proteína CheY-P invierte el sentido de giro: así la bacteria alterna entre nadar recto y reorientarse.',
        fn: ['Convierte el empuje de los estatores en giro.', 'Cambia el sentido de giro (quimiotaxis).'] },
      { id: 'estator', name: 'Estatores (MotA/MotB)', short: 'Estatores', color: '#5ec8ff', cat: 'Parte fija del motor', size: 'Hasta ≈ 11 unidades',
        desc: 'Unidades ancladas al peptidoglucano que rodean al rotor. Los protones fluyen a través de ellas a favor del gradiente, y ese flujo empuja al anillo C.',
        fn: ['Generan la fuerza (torque) del motor.'],
        fact: 'El motor suma o quita estatores según la carga: agrega “marchas” cuando le cuesta girar.' },
      { id: 'exportacion', name: 'Aparato de exportación', color: '#b388eb', cat: 'Secreción tipo III', size: '—',
        desc: 'Sistema de secreción ubicado dentro del anillo C que envía, por el interior hueco del flagelo, las proteínas que arman la varilla, el gancho y el filamento.',
        fn: ['Exporta las piezas del flagelo durante su armado.'] },
      { id: 'me', name: 'Membrana externa', color: '#e05a4b', cat: 'Envoltura Gram negativa', size: '≈ 7 nm',
        desc: 'Bicapa asimétrica propia de las Gram negativas: su cara externa está formada por lipopolisacárido (LPS) y tiene porinas.',
        fn: ['Barrera frente a antibióticos y detergentes.', 'Deja pasar moléculas pequeñas por las porinas.'],
        fact: 'El lípido A del LPS es la endotoxina que puede causar fiebre y shock séptico.' },
      { id: 'pg', name: 'Peptidoglucano', color: '#c0392b', cat: 'Pared celular', size: '≈ 2–7 nm',
        desc: 'Malla delgada de azúcares y péptidos ubicada en el periplasma, entre las dos membranas.',
        fn: ['Da forma y resiste la presión osmótica.', 'Es el blanco de la penicilina.'] },
      { id: 'mi', name: 'Membrana interna', color: '#f4d03f', cat: 'Membrana plasmática', size: '≈ 7 nm',
        desc: 'Membrana plasmática de la bacteria. La cadena respiratoria bombea protones a través de ella y genera la fuerza protón-motriz que alimenta al motor.',
        fn: ['Genera la fuerza protón-motriz.', 'Aloja el anillo MS y los estatores.'] },
    ],
  };

  /* Fuentes consultadas para los textos y el modelo */
  var FUENTES = [
    ['Alberts B. y col. Molecular Biology of the Cell, 4.ª ed. Garland Science, 2002 (NCBI Bookshelf).', 'https://www.ncbi.nlm.nih.gov/books/NBK21054/'],
    ['Cooper G. M. The Cell: A Molecular Approach, 2.ª ed. Sinauer, 2000 (NCBI Bookshelf).', 'https://www.ncbi.nlm.nih.gov/books/NBK9839/'],
    ['OpenStax. Biology 2e, cap. 4: Cell Structure. Rice University, 2018.', 'https://openstax.org/books/biology-2e/pages/4-introduction'],
    ['Singer S. J. y Nicolson G. L. The fluid mosaic model of the structure of cell membranes. Science 175, 720–731 (1972).', 'https://doi.org/10.1126/science.175.4023.720'],
    ['Ou H. D. y col. ChromEMT: visualizing 3D chromatin structure and compaction in interphase and mitotic cells. Science 357, eaag0025 (2017).', 'https://doi.org/10.1126/science.aag0025'],
    ['Kühlbrandt W. Structure and function of mitochondrial membrane protein complexes. BMC Biology 13, 89 (2015).', 'https://doi.org/10.1186/s12915-015-0201-x'],
    ['Mitochondrial Cristae Architecture and Functions: Lessons from Minimal Model Systems. Membranes 11, 465 (2021).', 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8306996/'],
    ['Anderson S. y col. Sequence and organization of the human mitochondrial genome. Nature 290, 457–465 (1981).', 'https://doi.org/10.1038/290457a0'],
    ['Ballabio A. The awesome lysosome. EMBO Molecular Medicine 8, 73–76 (2016).', 'https://doi.org/10.15252/emmm.201505966'],
    ['Berg H. C. The rotary motor of bacterial flagella. Annual Review of Biochemistry 72, 19–54 (2003).', 'https://doi.org/10.1146/annurev.biochem.72.121801.161737'],
    ['Magariyama Y. y col. Very fast flagellar rotation. Nature 371, 752 (1994).', 'https://doi.org/10.1038/371752b0'],
  ];

  window.CELULA_DATOS = { INFO: INFO, CMP: CMP, PRES: PRES, FUENTES: FUENTES };
})();
